workflows:
  android-workflow:
    name: Early Bird Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    triggering:
      events:
        - push
    scripts:
      - name: Generate Android Support Files
        script: |
          flutter create . --platforms=android
      - name: Bypass Android SDK 36 Compile Issue
        script: |
          echo "subprojects {
              afterEvaluate { project ->
                  if (project.hasProperty('android')) {
                      project.android {
                          compileSdkVersion 36
                      }
                  }
              }
          }" >> android/build.gradle
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --no-pub
          
          # தம்பி, எந்தப் பாதையில் ஏபிகே உருவானாலும் அதைத் தேடிக் கண்டுபிடிக்கும் அண்ணனின் ஸ்மார்ட் கட்டளை!
          mkdir -p build_output
          find build/app/outputs/ -name "*.apk" -exec cp {} build_output/Early_Bird_Stock_Book.apk \;
    artifacts:
      # இப்போ இந்த ஃபோல்டரிலிருந்து Codemagic கச்சிதமாக ஆப்பை எடுத்து உங்களிடம் கொடுத்துவிடும்ப்பா!
      - build_output/*.apk
